name:                Sediment
version:             0.1.0.0
github:              "githubuser/Sediment"
license:             BSD3
author:              "Georgian-Vlad Saioc"
maintainer:          "gsaioc18@student.aau.dk"
copyright:           "2020 Georgian-Vlad Saioc, Aalborg University"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Sediment#readme>

dependencies:
- base >= 4.7 && < 5
- array
- pretty-simple
- containers
- text
- directory
- split

library:
  source-dirs:
  - src
  exposed-modules:
  # Syntactic modules
  - Syntax.ErrM
  - Syntax.GetAst
  # Semantics modules
  - Semantics.StaticAnalysis
  - Semantics.Execute
  ## Domains-related
  - Semantics.Dom.Verify
  # Generation
  - Generation.Latex
  - Generation.Haskell

executables:
  Sediment-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Sediment

default-extensions:
  - LambdaCase

tests:
  Sediment-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Sediment
