name:                Sediment
version:             0.1.0.0
github:              "githubuser/Sediment"
license:             BSD3
author:              "Georgian-Vlad Saioc"
maintainer:          "gsaioc18@student.aau.dk"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Sediment#readme>

dependencies:
- base >= 4.7 && < 5
- array
- pretty-simple
- containers

library:
  source-dirs:
  - src
  exposed-modules:
  # Syntactic modules
  - Syntax.LexSediment
  - Syntax.AbsSediment
  - Syntax.ParSediment
  - Syntax.ErrM
  - Syntax.GetAst
  # Semantics modules
  - Semantics.Env
  - Semantics.Bind
  ## Well-formedness
  - Semantics.Domains.Wellformed.UniqueTags
  ## Expressions
  - Semantics.Expressions.Value

executables:
  Sediment-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Sediment

tests:
  Sediment-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Sediment
